In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris

In [5]:
df=pd.read_csv('auto-mpg.csv')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [6]:
df['model year']=df['model year']-df['model year'].min()

In [7]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,0,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,0,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,0,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,0,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,0,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,12,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,12,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,12,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,12,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,12,1,chevy s-10

In [11]:
df=df.drop('car name',axis=1)

In [12]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,18.0,8,307.0,130,3504,12.0,0,1
1,15.0,8,350.0,165,3693,11.5,0,1
2,18.0,8,318.0,150,3436,11.0,0,1
3,16.0,8,304.0,150,3433,12.0,0,1
4,17.0,8,302.0,140,3449,10.5,0,1
...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,12,1
394,44.0,4,97.0,52,2130,24.6,12,2
395,32.0,4,135.0,84,2295,11.6,12,1
396,28.0,4,120.0,79,2625,18.6,12,1
397,31.0,4,119.0,82,2720,19.4,12,1

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
dtypes: float64(3), int64(4), object(1)
memory usage: 25.0+ KB

In [17]:
df['horsepower']=df[df['horsepower']!='?']

In [18]:
df['horsepower']=df['horsepower'].astype('float64')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
dtypes: float64(4), int64(4)
memory usage: 25.0 KB

In [20]:
y=df['horsepower']
x=df.drop('horsepower',axis=1)

In [21]:
print(x.shape)
print(y.shape)

(398, 7)
(398,)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [24]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(318, 7)
(80, 7)
(318,)
(80,)

In [25]:
print(x_train)
print(y_train)

      mpg  cylinders  displacement  weight  acceleration  model year  origin
3    16.0          8         304.0    3433          12.0           0       1
18   27.0          4          97.0    2130          14.5           0       3
376  37.0          4          91.0    2025          18.2          12       3
248  36.1          4          91.0    1800          16.4           8       3
177  23.0          4         115.0    2694          15.0           5       2
..    ...        ...           ...     ...           ...         ...     ...
71   19.0          3          70.0    2330          13.5           2       3
106  12.0          8         350.0    4499          12.5           3       1
270  21.1          4         134.0    2515          14.8           8       3
348  37.7          4          89.0    2050          17.3          11       3
102  26.0          4          97.0    1950          21.0           3       2

[318 rows x 7 columns]
3      16.0
18     27.0
376    37.0
248    36.1
177    23.0
       ...
71     19.0
106    12.0
270    21.1
348    37.7
102    26.0
Name: horsepower, Length: 318, dtype: float64

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
model=LinearRegression()

In [28]:
model.fit(x_train,y_train)

LinearRegression()

In [29]:
y_pred=model.predict(x_test)
print(y_pred)

[33.  28.  19.  13.  14.  27.  24.  13.  17.  21.  15.  38.  26.  15.
 25.  12.  31.  17.  16.  31.  22.  22.  22.  33.5 18.  44.  26.  24.5
 18.1 12.  27.  36.  23.  24.  37.2 16.  21.  19.2 16.  29.  26.8 27.
 18.  10.  23.  36.  26.  25.  25.  25.  22.  34.1 32.4 13.  23.5 14.
 18.5 29.8 28.  19.  11.  33.  23.  21.  23.  25.  23.8 34.4 24.5 13.
 34.7 14.  15.  18.  25.  19.9 17.5 28.  29.  17. ]

In [30]:
model.coef_

array([ 1.00000000e+00, -5.30296067e-16,  4.52130793e-15, -5.08827933e-16,
       -6.31816149e-17,  3.14092478e-16,  2.13989533e-16])

In [31]:
model.intercept_

6.394884621840902e-13

In [32]:
x_test

      mpg  cylinders  displacement  weight  acceleration  model year  origin
198  33.0          4          91.0    1795          17.4           6       3
396  28.0          4         120.0    2625          18.6          12       1
33   19.0          6         232.0    2634          13.0           1       1
208  13.0          8         318.0    3940          13.2           6       1
93   14.0          8         318.0    4237          14.5           3       1
..    ...        ...           ...     ...           ...         ...     ...
249  19.9          8         260.0    3365          15.5           8       1
225  17.5          6         250.0    3520          16.4           7       1
367  28.0          4         112.0    2605          19.6          12       1
175  29.0          4          90.0    1937          14.0           5       2
285  17.0          8         305.0    3840          15.4           9       1

[80 rows x 7 columns]

In [33]:
y_pred

array([33. , 28. , 19. , 13. , 14. , 27. , 24. , 13. , 17. , 21. , 15. ,
       38. , 26. , 15. , 25. , 12. , 31. , 17. , 16. , 31. , 22. , 22. ,
       22. , 33.5, 18. , 44. , 26. , 24.5, 18.1, 12. , 27. , 36. , 23. ,
       24. , 37.2, 16. , 21. , 19.2, 16. , 29. , 26.8, 27. , 18. , 10. ,
       23. , 36. , 26. , 25. , 25. , 25. , 22. , 34.1, 32.4, 13. , 23.5,
       14. , 18.5, 29.8, 28. , 19. , 11. , 33. , 23. , 21. , 23. , 25. ,
       23.8, 34.4, 24.5, 13. , 34.7, 14. , 15. , 18. , 25. , 19.9, 17.5,
       28. , 29. , 17. ])

In [35]:
from sklearn.metrics import mean_squared_error,r2_score

In [36]:
mean_squared_error(y_pred,y_test)

2.6401360117665255e-26

In [37]:
r2_score(y_pred,y_test)

1.0